### PR TITLE
Optimise GulpChunk instantiation

### PR DESCRIPTION
**Pull request by willprice**
Constructing GulpChunks is very expensive and was consuming ~40% of the time spent data loading on of my projects. I've cached the creation of the GulpChunks so they are only initialised once.

### CODE REVIEW

**Comment by willprice** [comment]
I think the issue was due to the difference in dictionary implementation between pre-3.6 and 3.6 and above 

> The dict type has been reimplemented to use a more compact representation based on a proposal by Raymond Hettinger and similar to the PyPy dict implementation. This resulted in dictionaries using 20% to 25% less memory when compared to Python 3.5.
-- https://docs.python.org/3/whatsnew/3.6.html

I've fixed the issue and have reworked the constructor a bit to make more sense in light of the refactorings so it's a win-win!

**Comment by willprice** [comment]
@raghavgoyal14 Any chance you could take a look at this when you've got some time? It leads to a ~30-40% speedup on my machines, it's a shame not to have this integrated ;)

**Comment by raghavgoyal14** [comment]
@willprice it looks great. Thanks again for the contribution :)

**Comment by willprice** [comment]
Thanks @raghavgoyal14, much appreciated :D

**Pull request merged**
