### PR TITLE
Enable target transform for video dataset

### PR DESCRIPTION
**Pull request by tilt**

### CODE REVIEW

**Comment by esc** [comment]
It seems like the documentation of `GulpVideoDataset` is incomplete. Can you at least add `target_transform`? Also, do you have any idea why this is part of the class but not being used?

**Comment by tilt** [comment]
@esc I think it was simply forgotten. I'll add the docs now!

**Comment by esc** [comment]
@tilt thanks!

**Comment by esc** [comment]
waiting for travis to go green

**Pull request merged**
